# Built with Jekyll 3.2.0

# Setup
title:               "Allentown Diary"
tagline:             'In training for the USAAS at Camp Crane, Allentown, Pennsylvania, in July 1917'
description:         'An attempt to use Jekyll and Ed. to publish narratives enriched with Linked Open Data'
url:                 'https://wallandbinkley.com'
baseurl:             '/projects/2017/lodbook-ed'
status:              'Draft only, Sept. 2017'
googlemaps:
  apikey:            'AIzaSyAKirUd8aZPsiObFFH7c-hv5P1jpvBjaeQ'
  zoom:              14
noautolabel:         ['I', 'Our', 'church', 'the city']

# About/contact
author:
  name:              Peter Binkley
  url:               https://twitter.com/pabinkley

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

page_gen-dirs: true
page_gen:
  - data: 'people'
    name: 'name'
  - data: 'organisations'
    name: 'name'
  - data: 'places'
    name: 'name'
  - data: 'events'
    name: 'name'

data_types:
  people:
    template: 'person'
    dir: 'people'
    type: 'http://schema.org/Person'
  organisations:
    template: 'organisation'
    dir: 'organisations'
    type: 'http://schema.org/Organization'
  places:
    template: 'place'
    dir: 'places'
    type: 'http://schema.org/Place'
  events:
    template: 'event'
    dir: 'events'
    type: 'http://schema.org/Event'


# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


