# Built with Jekyll 3.2.0

# Setup
title:               LODBook-Ed
tagline:             'Linked Open Data for writers and historians'
description:         'An attempt to use Jekyll and Ed. to publish narratives enriched with Linked Open Data'
url:                 'http://wragge.github.io'
baseurl:             '/lodbook-ed'

# About/contact
author:
  name:              Tim Sherratt
  url:               https://twitter.com/wragge
  email:             tim@discontents.com.au

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

page_gen-dirs: true
page_gen:
  - data: 'data'
    name: 'name'

data_types:
  people:
    template: 'person'
    dir: 'people'
    type: 'http://schema.org/Person'
  organisations:
    template: 'organisation'
    dir: 'organisations'
    type: 'http://schema.org/Organization'


# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


